// Generated by CoffeeScript 1.6.3
(function() {
  chrome.app.runtime.onLaunched.addListener(function() {
    chrome.app.window.create('speech.html', {
      id: 'speech',
      frame: 'none',
      width: 700,
      height: 400
    });
  });

}).call(this);
