// Generated by CoffeeScript 1.6.3
(function() {
  var $, languagesList;

  $ = jQuery;

  languagesList = [['Afrikaans', ['af-ZA']], ['Bahasa Indonesia', ['id-ID']], ['Bahasa Melayu', ['ms-MY']], ['Català', ['ca-ES']], ['Čeština', ['cs-CZ']], ['Deutsch', ['de-DE']], ['English', ['en-AU', 'Australia'], ['en-CA', 'Canada'], ['en-IN', 'India'], ['en-NZ', 'New Zealand'], ['en-ZA', 'South Africa'], ['en-GB', 'United Kingdom'], ['en-US', 'United States']], ['Español', ['es-AR', 'Argentina'], ['es-BO', 'Bolivia'], ['es-CL', 'Chile'], ['es-CO', 'Colombia'], ['es-CR', 'Costa Rica'], ['es-EC', 'Ecuador'], ['es-SV', 'El Salvador'], ['es-ES', 'España'], ['es-US', 'Estados Unidos'], ['es-GT', 'Guatemala'], ['es-HN', 'Honduras'], ['es-MX', 'México'], ['es-NI', 'Nicaragua'], ['es-PA', 'Panamá'], ['es-PY', 'Paraguay'], ['es-PE', 'Perú'], ['es-PR', 'Puerto Rico'], ['es-DO', 'República Dominicana'], ['es-UY', 'Uruguay'], ['es-VE', 'Venezuela']], ['Euskara', ['eu-ES']], ['Français', ['fr-FR']], ['Galego', ['gl-ES']], ['Hrvatski', ['hr_HR']], ['IsiZulu', ['zu-ZA']], ['Íslenska', ['is-IS']], ['Italiano', ['it-IT', 'Italia'], ['it-CH', 'Svizzera']], ['Magyar', ['hu-HU']], ['Nederlands', ['nl-NL']], ['Norsk bokmål', ['nb-NO']], ['Polski', ['pl-PL']], ['Português', ['pt-BR', 'Brasil'], ['pt-PT', 'Portugal']], ['Română', ['ro-RO']], ['Slovenčina', ['sk-SK']], ['Suomi', ['fi-FI']], ['Svenska', ['sv-SE']], ['Türkçe', ['tr-TR']], ['български', ['bg-BG']], ['Pусский', ['ru-RU']], ['Српски', ['sr-RS']], ['한국어', ['ko-KR']], ['中文', ['cmn-Hans-CN', '普通话 (中国大陆)'], ['cmn-Hans-HK', '普通话 (香港)'], ['cmn-Hant-TW', '中文 (台灣)'], ['yue-Hant-HK', '粵語 (香港)']], ['日本語', ['ja-JP']], ['Lingua latīna', ['la']]];

  this.createLanguageList = function(name, callback) {
    var dialectSelect, languageIndex, languageSelect, populateDialectSelect, populateLanguageSelect;
    languageSelect = $('#' + name + '-names');
    dialectSelect = $('#' + name + '-dialects').hide();
    languageIndex = null;
    populateLanguageSelect = function() {
      var index, language, _i, _len;
      languageSelect.empty();
      $('<option>').appendTo(languageSelect).text('≡');
      for (index = _i = 0, _len = languagesList.length; _i < _len; index = ++_i) {
        language = languagesList[index];
        $('<option>').appendTo(languageSelect).val(index).text(language[0]);
      }
    };
    populateDialectSelect = function(languageIndex) {
      var dialect, _i, _len, _ref;
      dialectSelect.empty();
      $('<option>').appendTo(dialectSelect).text('≡');
      _ref = languagesList[languageIndex].slice(1);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        dialect = _ref[_i];
        $('<option>').appendTo(dialectSelect).val(dialect[0]).text(dialect[1]);
      }
    };
    languageSelect.on('change', function(event) {
      var languageOption;
      languageOption = $(':selected', languageSelect);
      if (!(languageIndex = languageOption.val())) {
        return;
      }
      if (languagesList[languageIndex][1].length === 1) {
        dialectSelect.hide();
        callback(languagesList[languageIndex][1][0], languagesList[languageIndex][0]);
        languageOption.prop('selected', false);
      } else {
        dialectSelect.show();
        populateDialectSelect(languageIndex);
      }
    });
    dialectSelect.on('change', function(event) {
      var dialectOption, languageCode;
      dialectOption = $(':selected', dialectSelect);
      if (!(languageCode = dialectOption.val())) {
        return;
      }
      callback(languageCode, languagesList[languageIndex][0] + ' - ' + dialectOption.text());
      dialectOption.prop('selected', false);
    });
    populateLanguageSelect();
  };

}).call(this);
