// Generated by CoffeeScript 1.6.3
(function() {
  var $, commands, prettifyRules;

  $ = jQuery;

  prettifyRules = [];

  $(function() {
    var message;
    message = {
      target: 'prettifyRules',
      command: 'load'
    };
    return parent.postMessage(message, '*');
  });

  commands = {
    magic: function(text) {
      var rule, _i, _len;
      for (_i = 0, _len = prettifyRules.length; _i < _len; _i++) {
        rule = prettifyRules[_i];
        text = text.replace.apply(text, rule);
      }
      return text;
    },
    parse: function(data) {
      var capitalize, error, line, obj, _i, _len, _ref;
      prettifyRules = [];
      capitalize = function(w) {
        return w.substr(0, 1).toUpperCase() + w.substr(1).toLowerCase();
      };
      _ref = data.split(/\r*\n+/);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        line = _ref[_i];
        if (/^\s*(#|$)/.test(line)) {

        } else if (/^\s*\[.+\]\s*$/.test(line)) {
          try {
            obj = eval(line);
          } catch (_error) {
            error = _error;
            return "Invalid JavaScript: " + error + ":\n" + line;
          }
          if (!$.isArray(obj) || obj.length !== 2) {
            return "Not an array of length 2:\n" + line;
          }
          prettifyRules.push(obj);
        } else {
          return "Invalid line:\n" + line;
        }
      }
      return null;
    }
  };

  window.addEventListener('message', function(event) {
    var data, message, _name;
    data = typeof commands[_name = event.data.command] === "function" ? commands[_name](event.data.data) : void 0;
    message = {
      target: 'prettifyRules',
      command: event.data.command,
      "return": data
    };
    event.source.postMessage(message, event.origin);
  });

}).call(this);
